name: CI
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff Linter
        run: ruff check --output-format=github . --fix
      - name: Run Ruff Formatter
        run: ruff format .  
      - name: Push changes
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet --cached HEAD || git commit -sm "Run Ruff Linter & Formatter"
          git push
